[LER-91] Create Program Cards
sirius-valley/lerni-web pull request #11
Opened 2024-02-27 20:10 UTC by schcolnikj

### **Create Program Cards**

**Questionnaire, Trivia and Students**

**TESTING:**
Go to` /create/program` and you should be able to see all changes. 

**CHANGES:**

1. Created Questionnaire Card with two states (no questionnaire assigned and questionnaire already assigned).
2. Created Trivia Card with two states similar to Qeustionnaire.
3. Created Students table with two states. 
4. Implemented tooltip for long names and emails over the student tables.
5. Re-designed the cards.
6. Updated the disabled button to look like the newer version.

2024-02-29 17:51 UTC, valenchus requested changes

2024-03-01 19:26 UTC, dipietronicolas commented on src/components/program/CreateProgram/index.tsx
Este archivo es una screen, tiene montados los componenes de create/program, hay que moverlo a screens.
Tambien tener en cuenta que el enrutador lo monte desde screens.

2024-03-01 19:32 UTC, dipietronicolas commented on src/components/program/ProgramQuestionnaire/index.tsx
> +          <StyledBox onClick={() => setShow(true)}>
1. A estos botones les hace falta un cursor: 'pointer' para indicar al usuario que son botones clickeables.
2. Hay que ampliar un poco la zona de click lateralmente, es muy corta.

2024-03-01 19:53 UTC, dipietronicolas commented on src/components/program/ProgramTrivia/index.tsx
> +          <StyledBox onClick={() => setShow(true)}>
Mismo que los botones de cuestionario, ampliar zona de click y poner cursor: 'pointer'

2024-03-01 19:54 UTC, dipietronicolas commented on src/components/program/ProgramStudents/Table/index.tsx
> +                <td style={{ textAlign: 'right', fontSize: 14, padding: '12px 0px 12px 10px' }}>
Mismo que los botones de cuestionario, ampliar zona de click y poner cursor: 'pointer'

2024-03-01 20:02 UTC, dipietronicolas commented on src/components/program/ProgramStudents/index.tsx
> +  const [show, setShow] = useState(false);
Si esta linea no hace nada saquemosla.

2024-03-01 20:04 UTC, dipietronicolas commented on src/components/program/ProgramQuestionnaire/index.tsx
> +  const [show, setShow] = useState(false);
Si esta linea no hace nada saquemosla

2024-03-01 20:04 UTC, dipietronicolas commented on src/components/program/ProgramTrivia/index.tsx
> +  const [show, setShow] = useState(false);
Afuera

2024-03-06 15:34 UTC, dipietronicolas approved these changes
LGTM

2024-03-06 19:17 UTC, merged